import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Container } from "@/shared/components/Container";
import { Header } from "@/shared/components/Header";
import { HEADER_TITLE } from "@/shared/consts/main";

const inter = Inter({ subsets: ["cyrillic", "latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} min-h-screen
      bg-gradient-to-r
      from-amber-300
      to-orange-500`}
      >
        <Header>{HEADER_TITLE}</Header>
        <Container>{children}</Container>
      </body>
    </html>
  );
}
